### ISSUE TITLE
As a developer, I want to crawl a huge dataset to test our blockchain implementation

### ISSUE THREAD

**Issue by humanjas** [deepweeb/B-B-W#197]
### Expected behavior
A huge dataset has been crawled

### Actual behavior
No dataset has been crawled.

### Steps to reproduce this behavior
-

### Definition of done
When it has been crawled

Member responsible: Jasper
Duration: 4h (2h reading in, 2h crawling)
Priority: Must
Claimed by: Jasper/ Ashay

**Comment by ymte** [comment]
You cannot just close an issue.
