### ISSUE TITLE
write a report (HCI)

### ISSUE THREAD

**Issue by nzarin** [deepweeb/B-B-W#206]
### Expected behavior
 We want to have the following documented:

* introduction
* method
* results
* discussion / conclusion
* appendix

### Actual behavior
none

### Steps to reproduce this behavior
First do all the tests and solve issue 201 till 205 then document it and adjust to the requirements. 

### Definition of done
This issue is solved when our report has the following chapters: 

* introduction
* method
* results
* discussion / conclusion
* appendix

Member responsible: Naqib
Duration: 4h 
Priority: Must
Claimed by: Naqib, Luat

**Comment by ymte** [comment]
The Overleaf document can be found [here](https://www.overleaf.com/10045042pjhssxcgtqpg).
