### ISSUE TITLE
Analyzing the Sprint feedback & making a plan to improve our Sprints. Res: Luat, Dur: 1h, Prio:A, Claimed: Luat&Naqib

### ISSUE THREAD

**Issue by deepweeb** [deepweeb/B-B-W#69]
### Expected behavior
Feedbacks from TA should be lived by.

### Actual behavior
Some feedback, are not lived by and should be fixed.

### Steps to reproduce the behavior
A planning (actually a copy from the feedback) is made and names of members whose issues belong to are mentioned so they can keep in mind/fix these issues.

See this file: https://docs.google.com/document/d/1gy1bIzMzQaOou71-iv7CIchkqLr8Kg01haT883cDDWU/edit#heading=h.1fbtrjqwa6yk

**Comment by nzarin** [comment]
done
