### ISSUE TITLE
Improve the project on SIG feedback before final deadline (23 June)

### ISSUE THREAD

**Issue by deepweeb** [deepweeb/B-B-W#72]
![image](https://user-images.githubusercontent.com/16018391/27083221-0fb275f6-5048-11e7-9f95-8612351ca8f3.png)

### Expected behavior
SIG analysis should have a score of at least 9 points.

### Actual behavior
As of 29 May, we only have a score of 6 points for the master branch of our repository.

### Steps to reproduce the behavior
Waiting until most if not all function is implemented. Aka a stable release before attempting to improve the SIG analysis score.

Res:Luat, Dur: 10h, Prio: Must, Claimed: Luat

**Comment by nzarin** [comment]
Latest score : 8 👍

**Comment by deepweeb** [comment]
DONE!
